name: cursus-environment
channels:
  - conda-forge
dependencies:
  - jupyter_contrib_nbextensions
  - pip
  - matplotlib
  - pandas
  - numpy
  - scipy
  - ipywidgets
  - scikit-rf
  - pip:
    - SchemDraw